[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
monitor_echo = true
upload_speed = 1500000

lib_deps =
    M5Unified @ 0.2.17
    h2zero/NimBLE-Arduino @ 2.5.0

monitor_filters = esp32_exception_decoder

board_upload.flash_size = 4MB

build_flags =
    -D CORE_DEBUG_LEVEL=3

[env:m5stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
monitor_echo = true
upload_speed = 1500000

lib_deps =
    M5Unified @ 0.2.17
    h2zero/NimBLE-Arduino @ 2.5.0

monitor_filters = esp32_exception_decoder

board_upload.flash_size = 8MB

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

[env:m5core-16mb]
platform = espressif32
board = m5stack-core-esp32-16M
framework = arduino
monitor_speed = 115200
monitor_echo = true
upload_speed = 921600

lib_deps =
    M5Unified @ 0.2.17
    h2zero/NimBLE-Arduino @ 2.5.0

monitor_filters = esp32_exception_decoder

board_upload.flash_size = 16MB

build_flags =
    -D CORE_DEBUG_LEVEL=3
